#ifndef WEBPAGE_H_
#define WEBPAGE_H_

const char INDEX_PAGE[] PROGMEM = {
		"<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"<head>\n"
		"    <meta charset=\"UTF-8\">\n"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n"
		"    <meta http-equiv=\"refresh\" content=\"10\">\n"
		"    <title>Dashboard</title>\n"
		"</head>\n"
		"<body style=\"text-align: center\">\n"
		"    <h1>Dashboard</h1>\n"
		"    <p>\n"
		"        <a href=\"/wifi\">WiFi Settings</a>\n"
		"        <a href=\"/server\">Server Settings</a>\n"
		"        <a href=\"/update\">Update Firmware</a>\n"
		"        <a href=\"/action/restart\">Restart</a>\n"
		"    </p>\n"
		"    <table style=\"margin: 0px auto\" border=2>\n"
		"        <tr>\n"
		"            <td>Free heap</td>\n"
		"            <td>%heap%</td>\n"
		"        </tr>\n"
		"        <tr>\n"
		"            <td>Last reset reason</td>\n"
		"            <td>%reset_reason%</td>\n"
		"        </tr>\n"
		"        <tr>\n"
		"            <td>SSID</td>\n"
		"            <td>%ssid%</td>\n"
		"        </tr>\n"
		"        <tr>\n"
		"            <td>RSSI</td>\n"
		"            <td>%rssi%</td>\n"
		"        </tr>\n"
		"        <tr>\n"
		"            <td>MQTT status</td>\n"
		"            <td>%mqtt_status%</td>\n"
		"        </tr>\n"
		"    </table>\n"
		"</body>\n"
		"</html>"
};

const char WIFI_CONFIG_PAGE[] PROGMEM = {
		"<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"<head>\n"
		"    <meta charset=\"UTF-8\">\n"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n"
		"    <title>WiFi Settings</title>\n"
		"</head>\n"
		"<body style=\"text-align:center\">\n"
		"    <h1>WiFi Settings</h1>\n"
		"    <p>\n"
		"        <a href=\"/scanwifi\">Scan WiFi</a>\n"
		"    </p>\n"
		"    <form action=\"/action/wificonfig\" method=\"post\">\n"
		"        SSID\n"
		"        <br>\n"
		"        <input type=\"text\" name=\"ssid\" value=\"%ssid%\">\n"
		"        <br>\n"
		"        Password\n"
		"        <br>\n"
		"        <input type=\"text\" name=\"password\" value=\"%password%\">\n"
		"        <br>\n"
		"        No password\n"
		"        <input type=\"checkbox\" name=\"nopass\" %nopass%>\n"
		"        <br><br>\n"
		"        <input type=\"submit\" value=\"Save\">\n"
		"    </form>\n"
		"</body>\n"
		"</html>"
};

const char SERVER_CONFIG_PAGE[] PROGMEM = {
		"<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"<head>\n"
		"    <meta charset=\"UTF-8\">\n"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n"
		"    <title>Server Settings</title>\n"
		"</head>\n"
		"<body style=\"text-align: center;\">\n"
		"    <h1>Server settings</h1>"
		"    <form action=\"/action/serverconfig\" method=\"POST\">\n"
		"        Server\n"
		"        <br>\n"
		"        <input name=\"server\" type=\"text\" value=\"%server%\">\n"
		"        <br>\n"
		"        Port\n"
		"        <br>\n"
		"        <input name=\"port\" type=\"number\" value=\"%port%\">\n"
		"        <br>\n"
		"        Client ID\n"
		"        <br>\n"
		"        <input name=\"client_id\" type=\"text\" value=\"%clid%\">\n"
		"        <br>\n"
		"        Username\n"
		"        <br>\n"
		"        <input name=\"username\" type=\"text\" value=\"%username%\">\n"
		"        <br>\n"
		"        Password\n"
		"        <br>\n"
		"        <input name=\"password\" type=\"password\" value=\"%password%\">\n"
		"        <br>\n"
		"        No Password\n"
		"        <input name=\"nopass\" type=\"checkbox\" %nopass%>\n"
		"        <br>\n"
		"        Topic\n"
		"        <br>\n"
		"        <input name=\"topic\" type=\"text\" value=\"%topic%\">\n"
		"        <br><br>\n"
		"        <input value=\"Save\" type=\"submit\">\n"
		"    </form>\n"
		"</body>\n"
		"</html>"
};

const char SCAN_WIFI_PAGE[] PROGMEM = {
		"<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"<head>\n"
		"    <meta charset=\"UTF-8\">\n"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n"
		"    <title>Scan WiFi</title>\n"
		"</head>\n"
		"<body style=\"text-align: center\">\n"
		"    <h1>Scan WiFi</h1>\n"
		"    <table style=\"margin: 0px auto\" border=2>\n"
		"    %wifi%\n"
		"    </table>\n"
		"</body>\n"
		"</html>"
};

const char UPDATE_PAGE[] PROGMEM = {
		"<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"<head>\n"
		"    <meta charset=\"UTF-8\">\n"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n"
		"    <title>Firmware Update</title>\n"
		"</head>\n"
		"<body style=\"text-align: center\">\n"
		"    <h1>Firmware Update</h1>\n"
		"    <form action=\"/action/update\" method=\"post\">\n"
		"        <input type=\"text\" name=\"fw_src\">\n"
		"        <input type=\"submit\" value=\"Update\">\n"
		"    </form>\n"
		"</body>\n"
		"</html>"
};

const char SUCCESS_PAGE[] PROGMEM = {
		"<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"<head>\n"
		"    <meta charset=\"UTF-8\">\n"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n"
		"    <title>Success</title>\n"
		"</head>\n"
		"<body style=\"text-align:center\">\n"
		"    <h1 style=\"color:green\">Success</h1>\n"
		"    <button onclick=\"history.back()\">Back</button>\n"
		"</body>\n"
		"</html>"
};

const char FAILED_PAGE[] PROGMEM = {
		"<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"<head>\n"
		"    <meta charset=\"UTF-8\">\n"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n"
		"    <title>Fail</title>\n"
		"</head>\n"
		"<body>\n"
		"    <h1 style=\"color:red;text-align:center\">Failed</h1>\n"
		"</body>\n"
		"</html>"
};

#endif /* WEBPAGE_H_ */
